# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp.xci
# IP: The module: 'gig_eth_pcs_pma_basex_gtp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp.xci
# IP: The module: 'gig_eth_pcs_pma_basex_gtp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /usersc/ng18731/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_eth_pcs_pma_basex_gtp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
