# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_example_4/top/top.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_example_4/top/top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_example_4/top/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_bit_ctrl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_byte_ctrl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_registers.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_top.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_package.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_addr_gen.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_alu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/rtl/core/neo430_application_image.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_bootloader_image.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_boot_rom.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_cfu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_control.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_cpu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_crc.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_dmem.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_gpio.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_imem.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_muldiv.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_pwm.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_reg_file.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_sysconfig.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_top_std_logic.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_timer.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_top.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_trng.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_usart.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_wb_interface.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_wdt.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/projects/tests/neotest/firmware/hdl/neo430_test_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top neo430_test_top -part xc7a35tfgg484-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef neo430_test_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file neo430_test_top_utilization_synth.rpt -pb neo430_test_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
