# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.cache/wt [current_project]
set_property parent.project_path C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/rtl/core/neo430_application_image.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_peephole_ram.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ram.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_decode_ipbus_example.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_example.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_eth/firmware/hdl/emac_hostbus_decl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_eth/firmware/hdl/eth_7s_1000basex_gtp.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/trans_arb.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_txtransactor_if_simple.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_tx_mux.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_status_buffer.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxtransactor_if_simple.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_shim.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_mux.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rarp_block.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_packet_parser.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_ipaddr_block.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_tx.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_rx.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_do_rx_reset.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_clock_crossing_if.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_byte_sum.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_status.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_resend.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_ping.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_payload.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_arp.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_buffer_selector.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_if_flat.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/led_stretcher.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_clock_div.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_util/firmware/hdl/clocks_7s_serdes.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/timing-board-firmware/boards/atfc/base_fw/synth/firmware/hdl/atfc_infra.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/timing-board-firmware/boards/atfc/base_fw/synth/firmware/hdl/top_atfc.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_bit_ctrl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_byte_ctrl.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_registers.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/components/opencores_i2c/firmware/hdl/i2c_master_top.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_wdt.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_wb_interface.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_usart.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_trng.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_timer.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_sysconfig.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_reg_file.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_pwm.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_package.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_muldiv.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_imem.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_gpio.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_dmem.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_crc.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_cpu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_control.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_cfu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_boot_rom.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_bootloader_image.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_top.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_alu.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_top_std_logic.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430/rtl/core/neo430_addr_gen.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/neo430_ipbus/projects/tests/neotest/firmware/hdl/neo430_test_top.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/trans_buffer.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/uc_if/firmware/hdl/uc_if.vhd
  C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/uc_spi_interface.vhd
}
read_ip -quiet C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp.xci
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/gig_eth_pcs_pma_basex_gtp_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/gig_eth_pcs_pma_basex_gtp/synth/gig_eth_pcs_pma_basex_gtp_ooc.xdc]

read_ip -quiet C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/temac_gbe_v9_0/temac_gbe_v9_0.xci
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/proj/neo430_final/top/top.srcs/sources_1/ip/temac_gbe_v9_0/synth/temac_gbe_v9_0_clocks.xdc]

read_ip -quiet C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/cgn/sdpram_32x9_16x10/sdpram_32x9_16x10.xci

read_ip -quiet C:/Users/USER/Desktop/projects/ATFC_IPBus_neo_test/neo430_test/myFwArea/src/ipbus-firmware/components/ipbus_slaves/firmware/cgn/sdpram_16x10_32x9/sdpram_16x10_32x9.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
