# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /usersc/ng18731/neo430_test/myFwArea/proj/neo430_final_1/top/top.srcs/sources_1/ip/sdpram_32x9_16x10/sdpram_32x9_16x10.xci
# IP: The module: 'sdpram_32x9_16x10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ng18731/neo430_test/myFwArea/proj/neo430_final_1/top/top.srcs/sources_1/ip/sdpram_32x9_16x10/sdpram_32x9_16x10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram_32x9_16x10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /usersc/ng18731/neo430_test/myFwArea/proj/neo430_final_1/top/top.srcs/sources_1/ip/sdpram_32x9_16x10/sdpram_32x9_16x10.xci
# IP: The module: 'sdpram_32x9_16x10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /usersc/ng18731/neo430_test/myFwArea/proj/neo430_final_1/top/top.srcs/sources_1/ip/sdpram_32x9_16x10/sdpram_32x9_16x10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdpram_32x9_16x10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
